### PR TITLE
Use lapin-futures instead of rust-amqp for pubsub_rabbitmq (api compatibility).

### PR DESCRIPTION
**Pull request by chaoticlonghair**
Use lapin-futures instead of rust-amqp for pubsub_rabbitmq (api compatibility).

### CODE REVIEW

**Review by u2 — APPROVED** [review]

**Comment by chaoticlonghair** [comment]
DO NOT MERGE!

We have to do more tests!

**Comment by chaoticlonghair** [comment]
The order of publisher thread and consumer thread have to be adjusted.

(but, the problem is still existed, when publisher is ok, and send some messages, but consumer is not ready to receive the receipts, some receipts will lost)

**Comment by zhangsoledad** [comment]
https://github.com/cryptape/cita-common/pull/135

**Comment by chaoticlonghair** [comment]
No significant performance improvement, and bring some weird bugs.

**Pull request closed without merging**
