### PR TITLE
rename Tendermint Bft

### PR DESCRIPTION
**Pull request by boundless-forest**
Tendermint rename Bft

update code fmt

update code fmt

update *.rs according to *.proto

code fmt

update jsonrpc-type

### CODE REVIEW

**Review by kaikai1024 — APPROVED** [review]

**Comment by driftluo** [comment]
You should to first pr to cita-proto, after merge, modify cita-common and update the commit hash of submodule @ouwenkg

**Comment by boundless-forest** [comment]
I have proposed pr to cita-proto and merged by u2 yesterday,  this pr use latest submodule cita-proto @driftluo

**Comment by boundless-forest** [comment]
Can this repo add some access control ? @driftluo

**Comment by driftluo** [comment]
From pr, you didn't update the submodule hash

**Review by kaikai1024 — CHANGES_REQUESTED** [review]
update proto

**Review by driftluo — DISMISSED** [review]

**Review by chaoticlonghair — DISMISSED** [review]

**Review by chaoticlonghair — APPROVED** [review]

**Review by kaikai1024 — APPROVED** [review]

**Pull request merged**
