### PR TITLE
support tx version 2

### PR DESCRIPTION
**Pull request by boundless-forest**
https://github.com/cryptape/cita/issues/508

### CODE REVIEW

**Review by KaoImin — APPROVED** [review]

**Review by kaikai1024 — APPROVED** [review]

**Comment by chaoticlonghair** [comment]
Why not just use `version < 3`? (only one operation)
In match: `version if version < 3`.

**Comment by boundless-forest** [comment]
Version 0 works differently from version 1 or 2. 

```rs
if version == 0 {
       verify_tx_req.set_chain_id(self.get_transaction().get_chain_id());
} else if version == 1 || version == 2 {
       verify_tx_req.set_chain_id_v1(self.get_transaction().get_chain_id_v1().to_vec());
}
```

**Comment by kaikai1024** [comment]
> Why not just use `version < 3`? (only one operation)
> In match: `version if version < 3`.

perfect.

**Comment by kaikai1024** [comment]
```
if version == 0 {
       verify_tx_req.set_chain_id(self.get_transaction().get_chain_id());
} else if version < 3 {
       verify_tx_req.set_chain_id_v1(self.get_transaction().get_chain_id_v1().to_vec());
}
```

@ouwenkg

**Comment by boundless-forest** [comment]
> ```
> if version == 0 {
>        verify_tx_req.set_chain_id(self.get_transaction().get_chain_id());
> } else if version < 3 {
>        verify_tx_req.set_chain_id_v1(self.get_transaction().get_chain_id_v1().to_vec());
> }
> ```
> 
> @ouwenkg

OK

**Pull request merged**
