### PR TITLE
temporarily use patched log4rs from fork

### PR DESCRIPTION
**Pull request by zeroqn**
This should fix one of ci failures.

### CODE REVIEW

**Review by u2 — COMMENTED** [review]
What's the problem before?

**Comment by zeroqn** [comment]
Actually, it's not ci failure here, but bitbucket.

**Comment by chaoticlonghair** [comment]
I do not like this.
And I do not disapprove it.

**Comment by zeroqn** [comment]
> I do not like this.
> And I do not disapprove it.

@yangby-cryptape  Do you mean directly point log4rs to fork instead of using patch?

**Pull request closed without merging**
