### PR TITLE
 add getVersion Method

### PR DESCRIPTION
**Pull request by luqz**
@ citaman

### CODE REVIEW

**Comment by kaikai1024** [comment]
Please clean up your commits.

**Comment by luqz** [comment]
> Please clean up your commits.
Maybe there need a rerun on CircleCI.

**Comment by kaikai1024** [comment]
> > Please clean up your commits.
> > Maybe there need a rerun on CircleCI.

ok

**Comment by kaikai1024** [comment]
@yangby-cryptape Would you please take a look?

**Pull request closed without merging**
