### PR TITLE
Prepare for the bors.

### PR DESCRIPTION
**Pull request by kaikai1024**

### CODE REVIEW

**Comment by kaikai1024** [comment]
Screenshot from 2019-03-19 14-16-08

**Comment by kaikai1024** [comment]
bors try

**Comment by kaikai1024** [comment]
bors try

**Review by boundless-forest — APPROVED** [review]

**Review by chaoticlonghair — APPROVED** [review]

**Comment by kaikai1024** [comment]
Will test it on my own repo first.

**Pull request closed without merging**
